version: '3.9'
services: 
  docker-frontend:
    build: 
      context: shooting-target
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    volumes:
      - ./shooting-target/src:/frontend/src
