import Head from 'next/head'
import Image from 'next/image'
import { Button } from 'react-bootstrap'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Destiny 2 Companion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Destiny 2 Companion!
        </h1>

        <p className={styles.description}>
          Companion that will enhance your Destiny 2 experience
        </p>

        <div className="d-flex justify-content-center">
          <Button size="lg">Login through Bungie.net</Button>
        </div>

        <div className={styles.grid}>
          <a className={styles.card}>
            <h2>Weapons</h2>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates, ducimus.</p>
          </a>

          <a className={styles.card}>
            <h2>Armors</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic, quam?</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>Jakub Hudymač</p>
      </footer>
    </div>
  )
}
